<#
.SYNOPSIS
Clones the read-only reference repositories listed in refs/manifest.tsv into refs/.

.DESCRIPTION
These are throwaway analysis clones, deliberately NOT git submodules: they are
read-only references, several have huge histories (gascity ~1.7 GB), and pinning
15 of them into .gitmodules would only add noise to this repo's status.

Reproducibility comes from two committed files instead:
  refs/manifest.tsv - what we pull and why
  refs/pinned.tsv   - the exact SHA each analysis conclusion was drawn from

Already-cloned repos are left untouched unless -Update is passed.

.PARAMETER Tier
Only sync repos in these tiers (e.g. -Tier 0,1). Default: all tiers.

.PARAMETER Update
Fetch and fast-forward existing clones instead of skipping them.

.EXAMPLE
pwsh scripts/sync-refs.ps1 -Tier 0,1
#>
[CmdletBinding()]
param(
    [int[]] $Tier,
    [switch] $Update
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$refsDir = Join-Path $repoRoot 'refs'
$manifestPath = Join-Path $refsDir 'manifest.tsv'
$pinnedPath = Join-Path $refsDir 'pinned.tsv'

if (-not (Test-Path $manifestPath)) { throw "Manifest not found: $manifestPath" }

# Strip comment lines before parsing; the header row is the first non-comment line.
$rows = Get-Content $manifestPath |
    Where-Object { $_ -notmatch '^\s*#' -and $_.Trim() } |
    ConvertFrom-Csv -Delimiter "`t"

if ($Tier) { $rows = $rows | Where-Object { [int]$_.tier -in $Tier } }
if (-not $rows) { throw 'No manifest rows selected.' }

Write-Host "Syncing $($rows.Count) reference repos into $refsDir" -ForegroundColor Cyan
$results = @()

foreach ($row in $rows) {
    $target = Join-Path $refsDir $row.dir
    $url = "https://github.com/$($row.repo).git"

    if (Test-Path (Join-Path $target '.git')) {
        if ($Update) {
            Write-Host "  update  $($row.dir)" -ForegroundColor DarkGray
            git -C $target fetch --quiet origin
            git -C $target merge --quiet --ff-only '@{u}'
        } else {
            Write-Host "  skip    $($row.dir) (already cloned)" -ForegroundColor DarkGray
        }
    } else {
        $cloneArgs = @('clone', '--quiet', '--single-branch')
        if ($row.depth -ne 'full') { $cloneArgs += @('--depth', $row.depth) }
        $cloneArgs += @($url, $target)

        Write-Host "  clone   $($row.dir) <- $($row.repo) (depth=$($row.depth))" -ForegroundColor Green
        git @cloneArgs
        if ($LASTEXITCODE -ne 0) { Write-Warning "clone failed: $($row.repo)"; continue }
    }

    $sha = (git -C $target rev-parse HEAD).Trim()
    $sizeMB = [math]::Round(
        ((Get-ChildItem $target -Recurse -File -Force | Measure-Object -Property Length -Sum).Sum / 1MB), 1)

    $results += [pscustomobject]@{
        dir     = $row.dir
        repo    = $row.repo
        tier    = $row.tier
        sha     = $sha
        size_mb = $sizeMB
        synced  = (Get-Date -Format 'yyyy-MM-dd')
    }
}

# pinned.tsv records the exact commit each analysis conclusion was drawn from.
# Merge with any rows for tiers we did not touch in this run.
$existing = @()
if (Test-Path $pinnedPath) {
    $existing = Get-Content $pinnedPath |
        Where-Object { $_ -notmatch '^\s*#' -and $_.Trim() } |
        ConvertFrom-Csv -Delimiter "`t" |
        Where-Object { $_.dir -notin $results.dir }
}

$header = @(
    '# Exact commits the analysis in docs/ was drawn from. Regenerated by scripts/sync-refs.ps1.'
    '# To reproduce a conclusion: clone the repo and `git checkout <sha>`.'
)
$body = @($existing + $results) |
    Sort-Object -Property { [int]$_.tier }, dir |
    ConvertTo-Csv -Delimiter "`t" -NoTypeInformation |
    ForEach-Object { $_ -replace '"', '' }

Set-Content -Path $pinnedPath -Value ($header + $body) -Encoding utf8

Write-Host ''
$results | Sort-Object -Property { [int]$_.tier }, dir | Format-Table -AutoSize
Write-Host "Total on disk: $([math]::Round(($results.size_mb | Measure-Object -Sum).Sum, 1)) MB" -ForegroundColor Cyan
Write-Host "Pinned SHAs written to refs/pinned.tsv" -ForegroundColor Cyan
